### ISSUE TITLE
是否能给出一个上下文长度的表格？

### ISSUE THREAD

**Issue by wuyeguo** [OrionStarAI/Orion#9]
从文档推测，Base的上下文长度是4096么？
是否能给出不同的模型的上下文长度列表？
Orion-14B-Base
Orion-14B-Chat
Orion-14B-LongChat: 320k.
Orion-14B-Chat-RAG: 
Orion-14B-Chat-Plugin: 
Orion-14B-Base-Int4: 
Orion-14B-Chat-Int4:

**Comment by chenxingphh** [comment]
> 从文档推测，Base的上下文长度是4096么？ 是否能给出不同的模型的上下文长度列表？ Orion-14B-Base Orion-14B-Chat Orion-14B-LongChat: 320k. Orion-14B-Chat-RAG: Orion-14B-Chat-Plugin: Orion-14B-Base-Int4: Orion-14B-Chat-Int4:

感谢关注。除了LongChat的版本的上下文不是4096，其他模型的上下文都是4096。

**Comment by Labmem009** [comment]
> > 从文档推测，Base的上下文长度是4096么？ 是否能给出不同的模型的上下文长度列表？ Orion-14B-Base Orion-14B-Chat Orion-14B-LongChat: 320k. Orion-14B-Chat-RAG: Orion-14B-Chat-Plugin: Orion-14B-Base-Int4: Orion-14B-Chat-Int4:
> 
> 感谢关注。除了LongChat的版本的上下文不是4096，其他模型的上下文都是4096。

RAG版本的上下文也是4k吗？请问下RAG使用方式和其他版本有没有什么区别？

**Comment by chenxingphh** [comment]
> > > 从文档推测，Base的上下文长度是4096么？ 是否能给出不同的模型的上下文长度列表？ Orion-14B-Base Orion-14B-Chat Orion-14B-LongChat: 320k. Orion-14B-Chat-RAG: Orion-14B-Chat-Plugin: Orion-14B-Base-Int4: Orion-14B-Chat-Int4:
> > 
> > 
> > 感谢关注。除了LongChat的版本的上下文不是4096，其他模型的上下文都是4096。
> 
> RAG版本的上下文也是4k吗？请问下RAG使用方式和其他版本有没有什么区别？

RAG也是4k，RAG的使用prompt可以看这里：https://huggingface.co/OrionStarAI/Orion-14B-Chat-RAG/blob/main/generation_utils.py

**Comment by wuyeguo** [comment]
多谢答复

**Comment by shibingli** [comment]
> 从文档推测，Base的上下文长度是4096么？ 是否能给出不同的模型的上下文长度列表？ Orion-14B-Base Orion-14B-Chat Orion-14B-LongChat: 320k. Orion-14B-Chat-RAG: Orion-14B-Chat-Plugin: Orion-14B-Base-Int4: Orion-14B-Chat-Int4:

Orion-14B-LongChat: 320k.   -->   这个传入大于4096的Tokens无法使用。
